language: java
before_install: mvn -q install -DskipTests=true -DfinalName=pilot-sc4-flink-kafka-consumer-$TRAVIS_TAG
deploy:
  provider: releases
  api_key:
    secure: Whm9mqO50IbBy4FK8HXc1Eww2v/0Fz1NqotIiMy3Conm9jUMEIn6hmUYzc+aVrhFYUuJ1OUXS6vKmhkTffOnXHeluH+BTncyHOMiS2glZC4qWTRhjkQqelFAG9ZQkCg/RA4B3oQ0jCdmxRJfNwy0NS+9FZ7qWhceWB3yOUvur2W3y0i9dZ3jj669dBGHQvToQwNjFLEKDOCTDoretukyKDoHqKbp7dheAt2KSR+KhHOLrM3EGg66/XFu/tX+cDmEleEJmsviyijDZD67DJbrHNZyRJpsvbCLcAiYBmpWWa5n045z3r/Bjo2/pn1qPovYnSt2T4+9t1mhZdM1XEv5TRT1zbvtYPsFYvbdScuxj88Tt8z6ERW0A9n01TMiadMuhC2BiRMyz3KtmGmpt7KQurv8d6HQl+mpOYXTDnaOqIqVokADV6l5o6+7YQew6k3PV11e/YyGneA0K8yFUs6GeTas/Wu61IMNnEXcJ/LzEeOmm3PY5J3XuJFXVW6V110UBFYJiZPaoD4oE0x32nUHJdBG8sfPwdpSpwiQZLQF0rvZj54RxVXLr3zxtoz2cFiU1A4aEK4KEQ2C96Gxr35wrtjCo+wdXFKw45NovWFkBRC+UdtaNbH+72dTEYo0K8DT0cofn5kYddaKsCpHRVLMmPBkSpzB6yWzoOLGKhRXrC4=
  file: target/pilot-sc4-flink-kafka-consumer-$TRAVIS_TAG-jar-with-dependencies.jar
  skip_cleanup: true
  on:
    repo: big-data-europe/pilot-sc4-flink-kafka-consumer
    tags: true
    all_branches: true
